### ISSUE TITLE
[Bug] Dockerfile wrong prefix directories for files copying

### ISSUE THREAD

**Issue by WinstonHChou** [dSPACE-IAC/dSPACE-IAC-sut-te-bridge#4]
The [Dockerfile](https://github.com/dSPACE-IAC/dSPACE-IAC-sut-te-bridge/blob/main/Dockerfile) should not include the sut-te-bridge/ prefix when copying files.

For example (and not limited to this instance):
```
RUN rosdep update && \  
    echo 'source /opt/ros/$ROS_DISTRO/local_setup.bash' >> /root/.bashrc  

RUN mkdir -p /opt/VESI/lib  
COPY sut-te-bridge/ros2_bridge_ws/src/sut_te_bridge/include/V-ESI-API/lib/linux/libVESIAPI.so /opt/VESI/lib/  

RUN ldconfig 
```
Please adjust accordingly in order to make the docker build work. Thank you!

**Comment by CarlGiest** [comment]
Yes, I see, this will not work as it is. The path is due to the folder structure required by our build pipeline, therefore I would keep the paths as they are. I will instead adjust the folder structure in github to match the one expected in the dockerfile. With that change building the image should work without any changes.
